### ISSUE TITLE
Backtesting - regression

### ISSUE THREAD

**Issue by datatalking** [TreyThomas93/python-trading-bot-with-thinkorswim#1]
What feature does your software have for single or multiple asset class testing based on historical data?

**Comment by TreyThomas93** [comment]
The program does not use any historical data. It simply relies on
strategies built within Thinkorswim.

**Comment by datatalking** [comment]
Do you know of such a tool I have between 60 and 190 years of old financial data that I would like to look for trends?

Is it like a multivariate regression or?

**Comment by TreyThomas93** [comment]
I do not unfortunately.

**Comment by TreyThomas93** [comment]
Answered
