### ISSUE TITLE
Use local database instead of external MongoDB

### ISSUE THREAD

**Issue by WildeWebMarketing** [TreyThomas93/python-trading-bot-with-thinkorswim#5]
How difficult would it be to change this to use a local database on my VPS where this is running instead of using an external service like MongoDB? Will the local community version of MongoDB work?

**Comment by TreyThomas93** [comment]
Not sure but I suppose it can be done.

**Comment by serendipity30** [comment]
This code works on local MongoDB. Tried on my desktop and installed everything locally and works like a charm.

**Comment by TreyThomas93** [comment]
Cool, thanks!
